import workerV31, { ParticipantVoteStore as V31ParticipantVoteStore } from './worker-v31.js';

const ADMIN_STORE_ID='__hmpp_tournament_admin__';
const STAGING_HOST='pied-piper-tournament-of-champions-v2-test';
const FIVE_MINUTES=5*60*1000;
const PLAYIN={
  PI01:['SONG26-019','SONG26-016'],PI02:['SONG26-042','SONG26-001'],PI03:['SONG26-052','SONG26-031'],PI04:['SONG26-051','SONG26-057'],
  PI05:['SONG26-069','SONG26-034'],PI06:['SONG26-028','SONG26-062'],PI07:['SONG26-044','SONG26-020'],PI08:['SONG26-066','SONG26-003']
};

const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
function store(env,id,action,payload={}){const stub=env.PARTICIPANT_VOTES.get(env.PARTICIPANT_VOTES.idFromName(id));return stub.fetch('https://vote-store.internal/'+action,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({participant_id:id,...payload})})}
function guessKey(round,songId){return round==='play-in'?songId:round+':'+songId}
function findGuess(guesses,round,songId){return guesses?.[guessKey(round,songId)]||Object.values(guesses||{}).find(g=>g?.round===round&&g?.song_id===songId)||null}
async function sessionFor(request,env,ctx){const r=await workerV31.fetch(new Request(new URL('/api/session',request.url),{method:'GET',headers:request.headers}),env,ctx);let body={};try{body=await r.clone().json()}catch{}return{response:r,session:body.session||null}}
async function directory(env){const r=await env.ASSETS.fetch(new Request('https://assets.local/data/2026/participants/public.json'));if(!r.ok)throw new Error('Participant directory unavailable.');return(await r.json()).participants||[]}
async function adminState(env){const r=await store(env,ADMIN_STORE_ID,'admin-state');if(!r.ok)throw new Error('Tournament state unavailable.');return(await r.json()).state||{schema_version:1,tournament:'HMPP-2026',results_visible:{},published_rounds:{'play-in':true},published_results:{},published_matchups:{},events:[]}}
async function writeGitJson(env,path,data,message){if(!env.GITHUB_TOKEN||!env.GITHUB_REPO)return;const branch=env.GITHUB_BRANCH||'feature/v2-auth-voting';const api='https://api.github.com/repos/'+env.GITHUB_REPO+'/contents/'+path;const headers={'authorization':'Bearer '+env.GITHUB_TOKEN,'accept':'application/vnd.github+json','user-agent':'HMPP-2026-Worker','x-github-api-version':'2022-11-28'};let sha;const current=await fetch(api+'?ref='+encodeURIComponent(branch),{headers});if(current.ok)sha=(await current.json()).sha;const bytes=new TextEncoder().encode(JSON.stringify(data,null,2)+'\n');let raw='';for(const b of bytes)raw+=String.fromCharCode(b);const body={message,content:btoa(raw),branch,...(sha?{sha}:{})};const put=await fetch(api,{method:'PUT',headers:{...headers,'content-type':'application/json'},body:JSON.stringify(body)});if(!put.ok)throw new Error('Git state mirror failed ('+put.status+').')}
async function saveAdminState(env,state,message){const r=await store(env,ADMIN_STORE_ID,'admin-set',{state});if(!r.ok)throw new Error('Tournament state could not be saved.');await writeGitJson(env,'data/2026/admin/publication-state.json',state,message);return state}
async function matchesForRound(env,round){if(round==='play-in')return Object.entries(PLAYIN).map(([match_id,songs])=>({match_id,round,songs}));const state=await adminState(env);return Array.isArray(state.published_matchups?.[round])?state.published_matchups[round].filter(m=>m.songs?.length===2):[]}
function hashSeed(text){let h=2166136261>>>0;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function pick(arr,r){return arr[Math.floor(r()*arr.length)]}
async function productionBallot(env,id){const repo=env.GITHUB_REPO||'natejeez/Pied-Piper-Tournament-of-Champions';const api='https://api.github.com/repos/'+repo+'/contents/data/2026/votes/by-participant/'+id+'.json?ref=main';const headers={'accept':'application/vnd.github+json','user-agent':'HMPP-2026-Worker','x-github-api-version':'2022-11-28',...(env.GITHUB_TOKEN?{'authorization':'Bearer '+env.GITHUB_TOKEN}:{})};const r=await fetch(api,{headers});if(!r.ok)return{votes:{},guesses:{}};const raw=await r.json();if(!raw.content)return raw;const text=atob(raw.content.replace(/\n/g,''));return JSON.parse(new TextDecoder().decode(Uint8Array.from(text,c=>c.charCodeAt(0))))}
function extractRoundBallot(source,round,matches,participantIds,seed){const voteSource=source?.votes||{},guessSource=source?.guesses||{},r=rng(seed),votes={},guesses={};let productionVotes=0,productionGuesses=0,simulatedVotes=0,simulatedGuesses=0;for(const m of matches){const existing=voteSource[m.match_id];const validExisting=existing?.round===round&&m.songs.includes(existing.song_id);const selected=validExisting?existing.song_id:pick(m.songs,r);if(validExisting){votes[m.match_id]=existing;productionVotes++}else{simulatedVotes++;votes[m.match_id]={vote_submission_id:'SIMVOTE-'+round+'-'+m.match_id+'-'+seed,matchup_submission_id:'SIMMATCH-'+round+'-'+m.match_id+'-'+seed,match_id:m.match_id,round,song_id:selected,submitted_at:new Date().toISOString(),vote_pool:'official',excluded_from_official_totals:false,simulated_for_test:true}}for(const songId of m.songs){const existingGuess=Object.values(guessSource).find(g=>g?.round===round&&g?.song_id===songId&&participantIds.includes(g.guessed_participant_id));const key=guessKey(round,songId);if(existingGuess){guesses[key]=existingGuess;productionGuesses++}else{simulatedGuesses++;guesses[key]={guess_submission_id:'SIMGUESS-'+round+'-'+songId+'-'+seed,guess_batch_id:'SIMMATCH-'+round+'-'+m.match_id+'-'+seed,matchup_submission_id:'SIMMATCH-'+round+'-'+m.match_id+'-'+seed,match_id:m.match_id,round,song_id:songId,guessed_participant_id:pick(participantIds,r),match_vote_song_id_at_submission:selected,match_vote_submission_id:votes[m.match_id].vote_submission_id,submitted_at:new Date().toISOString(),guess_pool:'official',excluded_from_official_guess_stats:false,simulated_for_test:true}}}}return{votes,guesses,productionVotes,productionGuesses,simulatedVotes,simulatedGuesses}}
async function buildRoundStats(env,round,activeId=null){const matches=await matchesForRound(env,round),people=(await directory(env)).filter(p=>!p.is_test),states=await Promise.all(people.map(async p=>{const r=await store(env,p.id,'state',{is_test:false});return{id:p.id,name:p.name,state:r.ok?await r.json():{votes:{},guesses:{}}}})),nameById=Object.fromEntries(people.map(p=>[p.id,p.name])),allGuessCounts={};const active=activeId?states.find(x=>x.id===activeId):null;const rows=matches.map(m=>{const counts=Object.fromEntries(m.songs.map(s=>[s,0]));for(const entry of states){const v=entry.state.votes?.[m.match_id];if(v&&counts[v.song_id]!==undefined)counts[v.song_id]++}const total=Object.values(counts).reduce((a,b)=>a+b,0),ordered=Object.entries(counts).sort((a,b)=>b[1]-a[1]),winner=ordered.length>1&&ordered[0][1]!==ordered[1][1]?ordered[0][0]:null;const activeVote=active?.state.votes?.[m.match_id]?.song_id||null;return{id:m.match_id,round,total_votes:total,winner_song_id:winner,tied:!winner&&total===people.length,songs:m.songs.map(songId=>{const gc={};for(const entry of states){const g=findGuess(entry.state.guesses,round,songId);if(g?.guessed_participant_id){gc[g.guessed_participant_id]=(gc[g.guessed_participant_id]||0)+1;allGuessCounts[g.guessed_participant_id]=(allGuessCounts[g.guessed_participant_id]||0)+1}}const top=Object.entries(gc).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,3).map(([id,count])=>({id,name:nameById[id]||id,count}));const ag=active?findGuess(active.state.guesses,round,songId):null;return{id:songId,vote_count:counts[songId],vote_share:total?counts[songId]/total:0,top_guesses:top,active_user_guess_id:ag?.guessed_participant_id||null,active_user_guess_name:ag?(nameById[ag.guessed_participant_id]||ag.guessed_participant_id):null}}),active_user_ballot:{selected_song_id:activeVote}}});const margins=rows.filter(x=>x.songs.length===2).map(x=>({id:x.id,margin:Math.abs(x.songs[0].vote_count-x.songs[1].vote_count)})),most=Object.entries(allGuessCounts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0];return{round,source:'durable-object-aggregate',voter_count:people.length,matches:rows,summary:{closest:[...margins].sort((a,b)=>a.margin-b.margin)[0]||null,widest:[...margins].sort((a,b)=>b.margin-a.margin)[0]||null,most_guessed:most?{id:most[0],name:nameById[most[0]]||most[0],count:most[1]}:null}}}
async function simulateRoundFixture(request,env,ctx){const {response,session}=await sessionFor(request,env,ctx);if(!response.ok)return response;if(!session?.is_test||session.participant_id!=='test-voter')return json({error:'Test Voter administrator access required.'},403);const body=await request.json().catch(()=>({})),round=body.round||'play-in',matches=await matchesForRound(env,round);if(!matches.length)return json({error:'No published/resolved matchups exist for this round.'},409);const people=(await directory(env)).filter(p=>!p.is_test),ids=people.map(p=>p.id),seed=(Date.now()&0xffffffff)>>>0,seeded=[];for(const p of people){const source=await productionBallot(env,p.id),completed=extractRoundBallot(source,round,matches,ids,hashSeed(round+':'+p.id+':'+seed));const s=await store(env,p.id,'admin-seed-round',{round,votes:completed.votes,guesses:completed.guesses,is_test:false});if(!s.ok)throw new Error('Could not seed '+p.name+'.');seeded.push({participant_id:p.id,name:p.name,production_votes:completed.productionVotes,production_guesses:completed.productionGuesses,simulated_votes:completed.simulatedVotes,simulated_guesses:completed.simulatedGuesses})}return json({ok:true,round,seed,seeded,stats:await buildRoundStats(env,round,'test-voter')})}
async function participantStatus(request,env,ctx){const {response,session}=await sessionFor(request,env,ctx);if(!response.ok)return response;if(!session?.is_test)return json({error:'Administrator access required.'},403);const round=new URL(request.url).searchParams.get('round')||'play-in',matches=await matchesForRound(env,round),people=(await directory(env)).filter(p=>!p.is_test),rows=[];for(const p of people){const r=await store(env,p.id,'state',{is_test:false}),state=r.ok?await r.json():{votes:{},guesses:{}};let submitted=0;for(const m of matches){const vote=state.votes?.[m.match_id],complete=!!vote&&m.songs.every(s=>!!findGuess(state.guesses,round,s));if(complete)submitted++}rows.push({participant_id:p.id,name:p.name,submitted_matchups:submitted,expected_matchups:matches.length,complete:submitted===matches.length})}return json({round,all_complete:rows.length>0&&rows.every(x=>x.complete),participants:rows})}
async function togglePublication(request,env,ctx,kind){const {response,session}=await sessionFor(request,env,ctx);if(!response.ok)return response;if(!session?.is_test)return json({error:'Administrator access required.'},403);const body=await request.json().catch(()=>({})),round=body.round;if(!round)return json({error:'Round is required.'},400);const state=await adminState(env),now=new Date().toISOString();state.events=state.events||[];if(kind==='results'){state.results_visible=state.results_visible||{};state.published_results=state.published_results||{};state.results_visible[round]=false;delete state.published_results[round];state.events.push({at:now,type:'results-unpublished',round,by:session.participant_id})}else{state.published_rounds=state.published_rounds||{};state.published_matchups=state.published_matchups||{};state.published_rounds[round]=false;delete state.published_matchups[round];state.events.push({at:now,type:'round-unpublished',round,by:session.participant_id})}await saveAdminState(env,state,'Unpublish HMPP '+kind+': '+round);return json({ok:true,state})}

function patchGuessing(source){
  const marker="  function matchSongs(match){return $$('.song[data-song-id]',match)}";
  if(source.includes(marker)&&!source.includes('function guessFor(round,songId)')){
    const addition=marker+"\n  function guessKey(round,songId){return round==='play-in'?songId:round+':'+songId}\n  function guessFor(round,songId){return sessionState?.guesses?.[guessKey(round,songId)]||Object.values(sessionState?.guesses||{}).find(g=>g?.round===round&&g?.song_id===songId)||null}";
    source=source.replace(marker,addition);
  }
  source=source.replace(/const saved=sessionState\?\.guesses\?\.\[sid\];/g,'const saved=guessFor(match.dataset.round,sid);');
  source=source.replace(/sessionState\.guesses\[g\.song_id\]=g/g,'sessionState.guesses[guessKey(match.dataset.round,g.song_id)]=g');
  source=source.replace(/sessionState\?\.guesses\?\.\[s\.dataset\.songId\]/g,'guessFor(match.dataset.round,s.dataset.songId)');
  source=source.replace(/sessionState\.guesses\?\.\[s\.dataset\.songId\]/g,'guessFor(match.dataset.round,s.dataset.songId)');
  return source;
}

export default{
  async fetch(request,env,ctx){
    const url=new URL(request.url),staging=url.hostname.includes(STAGING_HOST);
    if(staging&&url.pathname==='/api/admin/simulate-round'&&request.method==='POST')try{return await simulateRoundFixture(request,env,ctx)}catch(e){console.error(e);return json({error:e.message||'Simulation failed.'},500)}
    if(staging&&url.pathname==='/api/admin/participant-status'&&request.method==='GET')try{return await participantStatus(request,env,ctx)}catch(e){return json({error:e.message},500)}
    if(staging&&url.pathname==='/api/admin/unpublish-results'&&request.method==='POST')try{return await togglePublication(request,env,ctx,'results')}catch(e){return json({error:e.message},500)}
    if(staging&&url.pathname==='/api/admin/unpublish-round'&&request.method==='POST')try{return await togglePublication(request,env,ctx,'round')}catch(e){return json({error:e.message},500)}
    if(url.pathname==='/api/published-results'&&request.method==='GET'){
      const {response,session}=await sessionFor(request,env,ctx);if(!response.ok)return response;
      const round=url.searchParams.get('round')||'play-in',state=await adminState(env);
      if(state.results_visible?.[round]!==true)return json({error:'Results are not published for this round.'},404);
      return json({stats:await buildRoundStats(env,round,session.participant_id)});
    }
    if(staging&&url.pathname==='/api/admin/round'&&request.method==='GET'){
      const response=await workerV31.fetch(request,env,ctx);if(!response.ok)return response;
      const body=await response.json(),round=url.searchParams.get('round')||'play-in';
      const {session}=await sessionFor(request,env,ctx);body.stats=await buildRoundStats(env,round,session?.participant_id||null);return json(body);
    }
    if(url.pathname==='/guessing.js'){
      const response=await workerV31.fetch(request,env,ctx);if(!response.ok)return response;
      const source=patchGuessing(await response.text());const headers=new Headers(response.headers);headers.set('content-type','application/javascript; charset=utf-8');headers.set('cache-control','no-store');headers.set('x-hmpp-build','v2.36-round-safe');return new Response(source,{status:response.status,headers});
    }
    if(staging&&url.pathname==='/stats-v3.js')return new Response('/* superseded by V2 staging controls */',{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store'}});
    const response=await workerV31.fetch(request,env,ctx);
    if(staging&&!url.pathname.startsWith('/api/')&&(url.pathname==='/'||url.pathname==='/index.html')&&response.ok&&(response.headers.get('content-type')||'').includes('text/html')){
      const transformed=new HTMLRewriter().on('head',{element(el){el.append('<link rel="stylesheet" href="/v32.css?v=2.36.0"><script src="/v32-controls.js?v=2.36.0" defer></script><script src="/published-results-v35.js?v=2.36.0" defer></script>',{html:true})}}).transform(response);const headers=new Headers(transformed.headers);headers.set('x-hmpp-build','v2.36-safe-rebuild');headers.set('cache-control','no-store');return new Response(transformed.body,{status:response.status,headers});
    }
    return response;
  }
};

export class ParticipantVoteStore extends V31ParticipantVoteStore{
  async fetch(request){
    const action=new URL(request.url).pathname.slice(1),body=await request.clone().json().catch(()=>({}));
    if(action==='matchup-submit'&&body.round!=='play-in'){
      if(body.participant_id)await this.state.storage.put('participant_id',body.participant_id);
      if(typeof body.is_test==='boolean')await this.state.storage.put('is_test',body.is_test);
      const votes=(await this.state.storage.get('votes'))||{},guesses=(await this.state.storage.get('guesses'))||{},existingVote=votes[body.match_id],incoming=Array.isArray(body.guesses)?body.guesses:[];
      if(existingVote&&existingVote.song_id!==body.song_id)return json({error:'A vote has already been submitted for this matchup.'},409);
      for(const g of incoming){const key=guessKey(body.round,g.song_id),ex=guesses[key];if(ex&&ex.guessed_participant_id!==g.guessed_participant_id)return json({error:'A submitter guess has already been submitted for this song in this round.'},409)}
      const test=(await this.state.storage.get('is_test'))===true,matchupId=existingVote?.matchup_submission_id||((test?'TESTMATCHUP-':'MATCHUP-')+crypto.randomUUID()),submittedAt=new Date().toISOString();let vote=existingVote;
      if(!vote){vote={vote_submission_id:(test?'TESTVOTE-':'VOTE-')+crypto.randomUUID(),matchup_submission_id:matchupId,match_id:body.match_id,round:body.round,song_id:body.song_id,submitted_at:submittedAt,vote_pool:test?'test':'official',excluded_from_official_totals:test};votes[body.match_id]=vote}
      const returned=[];
      for(const g of incoming){const key=guessKey(body.round,g.song_id);if(guesses[key]){returned.push(guesses[key]);continue}const rec={guess_submission_id:(test?'TESTGUESS-':'GUESS-')+crypto.randomUUID(),guess_batch_id:matchupId,matchup_submission_id:matchupId,match_id:body.match_id,round:body.round,song_id:g.song_id,guessed_participant_id:g.guessed_participant_id,match_vote_song_id_at_submission:vote.song_id,match_vote_submission_id:vote.vote_submission_id,submitted_at:submittedAt,guess_pool:test?'test':'official',excluded_from_official_guess_stats:test};guesses[key]=rec;returned.push(rec)}
      await this.state.storage.put('votes',votes);await this.state.storage.put('guesses',guesses);await this.state.storage.setAlarm(Date.now()+FIVE_MINUTES);return json({ok:true,matchup_submission_id:matchupId,vote,guesses:returned});
    }
    return super.fetch(request);
  }
}
