import baseWorker, { ParticipantVoteStore as BaseParticipantVoteStore } from './worker.js';

const MATCHES = {"PI01":{"round":"play-in","songs":["SONG26-019","SONG26-016"]},"PI02":{"round":"play-in","songs":["SONG26-042","SONG26-001"]},"PI03":{"round":"play-in","songs":["SONG26-052","SONG26-031"]},"PI04":{"round":"play-in","songs":["SONG26-051","SONG26-057"]},"PI05":{"round":"play-in","songs":["SONG26-069","SONG26-034"]},"PI06":{"round":"play-in","songs":["SONG26-028","SONG26-062"]},"PI07":{"round":"play-in","songs":["SONG26-044","SONG26-020"]},"PI08":{"round":"play-in","songs":["SONG26-066","SONG26-003"]},"M001":{"round":"round-of-64","songs":["SONG26-046","SONG26-061"]},"M002":{"round":"round-of-64","songs":["SONG26-004","SONG26-050"]},"M003":{"round":"round-of-64","songs":["SONG26-055"]},"M004":{"round":"round-of-64","songs":["SONG26-068","SONG26-021"]},"M005":{"round":"round-of-64","songs":["SONG26-072"]},"M006":{"round":"round-of-64","songs":["SONG26-022","SONG26-029"]},"M007":{"round":"round-of-64","songs":["SONG26-007","SONG26-032"]},"M008":{"round":"round-of-64","songs":["SONG26-065","SONG26-010"]},"M009":{"round":"round-of-64","songs":["SONG26-071","SONG26-013"]},"M010":{"round":"round-of-64","songs":["SONG26-009","SONG26-059"]},"M011":{"round":"round-of-64","songs":["SONG26-011","SONG26-056"]},"M012":{"round":"round-of-64","songs":["SONG26-067","SONG26-008"]},"M013":{"round":"round-of-64","songs":["SONG26-033"]},"M014":{"round":"round-of-64","songs":["SONG26-037"]},"M015":{"round":"round-of-64","songs":["SONG26-025","SONG26-045"]},"M016":{"round":"round-of-64","songs":["SONG26-027","SONG26-039"]},"M017":{"round":"round-of-64","songs":["SONG26-012","SONG26-058"]},"M018":{"round":"round-of-64","songs":["SONG26-018","SONG26-040"]},"M019":{"round":"round-of-64","songs":["SONG26-038"]},"M020":{"round":"round-of-64","songs":["SONG26-070","SONG26-048"]},"M021":{"round":"round-of-64","songs":["SONG26-053","SONG26-005"]},"M022":{"round":"round-of-64","songs":["SONG26-036","SONG26-041"]},"M023":{"round":"round-of-64","songs":["SONG26-060","SONG26-023"]},"M024":{"round":"round-of-64","songs":["SONG26-017"]},"M025":{"round":"round-of-64","songs":["SONG26-043","SONG26-024"]},"M026":{"round":"round-of-64","songs":["SONG26-006"]},"M027":{"round":"round-of-64","songs":["SONG26-047","SONG26-015"]},"M028":{"round":"round-of-64","songs":["SONG26-054","SONG26-002"]},"M029":{"round":"round-of-64","songs":["SONG26-026","SONG26-035"]},"M030":{"round":"round-of-64","songs":["SONG26-063","SONG26-049"]},"M031":{"round":"round-of-64","songs":["SONG26-014","SONG26-030"]},"M032":{"round":"round-of-64","songs":["SONG26-064"]}};
const PLAYIN_TO_R64={PI01:'M003',PI02:'M013',PI03:'M005',PI04:'M026',PI05:'M032',PI06:'M014',PI07:'M019',PI08:'M024'};
const ADMIN_STORE_ID='__hmpp_tournament_admin__';
const RESET_MARKER='test-voter-round-of-64-reset-v23';
const SESSION_COOKIE='hmpp_session';
const FIVE_MINUTES=5*60*1000;

const utf8=s=>new TextEncoder().encode(s);
const text=b=>new TextDecoder().decode(b);
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}})}
function bytesToBase64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function base64ToBytes(s){const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function b64url(bytes){return bytesToBase64(bytes).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromB64url(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return base64ToBytes(s)}
async function hmac(secret,data){const key=await crypto.subtle.importKey('raw',utf8(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',key,utf8(data)))}
async function readSession(request,env){const cookie=request.headers.get('cookie')||'';const m=cookie.match(new RegExp('(?:^|;\\s*)'+SESSION_COOKIE+'=([^;]+)'));if(!m)return null;const [body,sig]=m[1].split('.');if(!body||!sig)return null;const expected=b64url(await hmac(env.SESSION_SECRET,body));if(sig!==expected)return null;try{const p=JSON.parse(text(fromB64url(body)));return p?.sub&&p?.exp&&Date.now()<=p.exp?p:null}catch{return null}}
async function participants(env){const r=await env.ASSETS.fetch(new Request(new URL('/data/2026/participants/public.json','https://assets.local')));if(!r.ok)throw new Error('Participant list unavailable');return (await r.json()).participants}
const isTest=p=>p?.is_test===true||p?.id==='test-voter';
function store(env,id,action,payload={}){const stub=env.PARTICIPANT_VOTES.get(env.PARTICIPANT_VOTES.idFromName(id));return stub.fetch('https://vote-store.internal/'+action,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({participant_id:id,...payload})})}
function defaultTournamentState(){return{schema_version:1,tournament:'HMPP-2026',results_visible:{},published_rounds:{'play-in':true},published_results:{},published_matchups:{},events:[]}}
async function getTournamentState(env){const r=await store(env,ADMIN_STORE_ID,'admin-state');if(!r.ok)throw new Error('Tournament state unavailable');return (await r.json()).state||defaultTournamentState()}
async function writeGitJson(env,path,data,message){if(!env.GITHUB_TOKEN||!env.GITHUB_REPO)throw new Error('GitHub mirror is not configured');const branch=env.GITHUB_BRANCH||'main',api=`https://api.github.com/repos/${env.GITHUB_REPO}/contents/${path}`,headers={'authorization':`Bearer ${env.GITHUB_TOKEN}`,'accept':'application/vnd.github+json','user-agent':'HMPP-2026-Worker','x-github-api-version':'2022-11-28'};let sha;const current=await fetch(api+'?ref='+encodeURIComponent(branch),{headers});if(current.ok)sha=(await current.json()).sha;else if(current.status!==404)throw new Error('GitHub read failed: '+current.status);const content=bytesToBase64(utf8(JSON.stringify(data,null,2)+'\n')),body={message,content,branch,...(sha?{sha}:{})};let put=await fetch(api,{method:'PUT',headers:{...headers,'content-type':'application/json'},body:JSON.stringify(body)});if(put.status===409){const latest=await fetch(api+'?ref='+encodeURIComponent(branch),{headers});if(latest.ok){body.sha=(await latest.json()).sha;put=await fetch(api,{method:'PUT',headers:{...headers,'content-type':'application/json'},body:JSON.stringify(body)})}}if(!put.ok)throw new Error('GitHub write failed: '+put.status+' '+await put.text());return put.json()}
async function saveTournamentState(env,state,message){const r=await store(env,ADMIN_STORE_ID,'admin-set',{state});if(!r.ok)throw new Error('Tournament state could not be saved');await writeGitJson(env,'data/2026/admin/publication-state.json',state,message);return state}
function baseMatches(round){return Object.entries(MATCHES).filter(([,m])=>m.round===round).map(([match_id,m])=>({match_id,round:m.round,songs:[...m.songs]}))}
function buildR64(results){const winners=Object.fromEntries(results.map(r=>[r.match_id,r.winner_song_id])),reverse=Object.fromEntries(Object.entries(PLAYIN_TO_R64).map(([pi,m])=>[m,pi]));return baseMatches('round-of-64').map(m=>m.songs.length===2?m:{...m,songs:winners[reverse[m.match_id]]?[winners[reverse[m.match_id]],...m.songs]:[...m.songs],source_play_in:reverse[m.match_id]||null})}
async function resolvedMatches(env,round,{preview=false}={}){if(round==='play-in')return baseMatches(round);if(round!=='round-of-64')return[];const state=await getTournamentState(env),pub=state.published_matchups?.[round];if(Array.isArray(pub)&&pub.length)return pub;if(preview){const prev=await aggregate(env,'play-in');if(prev.advancement_ready)return buildR64(prev.results)}return[]}
async function effectiveMatch(env,matchId,{preview=false}={}){const base=MATCHES[matchId];if(!base)return null;if(base.songs.length===2)return{match_id:matchId,round:base.round,songs:[...base.songs]};const all=await resolvedMatches(env,base.round,{preview});return all.find(m=>m.match_id===matchId)||null}
async function aggregate(env,round){const matches=round==='play-in'?baseMatches(round):await resolvedMatches(env,round),official=(await participants(env)).filter(p=>!isTest(p));if(!matches.length)return{round,supported:false,complete:false,advancement_ready:false,official_participants:official.length,expected_votes:0,received_votes:0,ties:[],results:[]};const states=await Promise.all(official.map(async p=>{const r=await store(env,p.id,'state',{is_test:false});return r.ok?{id:p.id,votes:(await r.json()).votes||{}}:{id:p.id,votes:{}}}));let received=0;const ties=[],results=[];for(const m of matches){const counts=Object.fromEntries(m.songs.map(s=>[s,0]));for(const st of states){const v=st.votes[m.match_id];if(v&&Object.prototype.hasOwnProperty.call(counts,v.song_id)){counts[v.song_id]++;received++}}const total=Object.values(counts).reduce((a,b)=>a+b,0),complete=total===official.length,ordered=Object.entries(counts).sort((a,b)=>b[1]-a[1]),tied=complete&&ordered.length>1&&ordered[0][1]===ordered[1][1];if(tied)ties.push(m.match_id);results.push({match_id:m.match_id,round,songs:m.songs.map(song_id=>({song_id,votes:counts[song_id]})),total_votes:total,complete,tied,winner_song_id:complete&&!tied?ordered[0][0]:null})}const complete=results.every(r=>r.complete);return{round,supported:true,complete,advancement_ready:complete&&ties.length===0,official_participants:official.length,expected_votes:official.length*matches.length,received_votes:received,ties,results}}
function publicState(state){const visible={};for(const [round,on] of Object.entries(state.results_visible||{}))if(on&&state.published_results?.[round])visible[round]=state.published_results[round];return{schema_version:state.schema_version||1,results_visible:state.results_visible||{},published_rounds:state.published_rounds||{'play-in':true},published_results:visible,published_matchups:state.published_matchups||{}}}

export default {
  async fetch(request,env,ctx){
    const url=new URL(request.url);
    if(!url.pathname.startsWith('/api/'))return baseWorker.fetch(request,env,ctx);
    if(url.pathname==='/api/participants'||url.pathname==='/api/login'||url.pathname==='/api/session'||url.pathname==='/api/logout')return baseWorker.fetch(request,env,ctx);
    try{
      const session=await readSession(request,env);if(!session)return json({error:'Authentication required.'},401);
      if(url.pathname==='/api/votes'&&request.method==='POST')return json({error:'Complete the song choice and both submitter guesses, then submit the matchup together.'},409);
      if(url.pathname==='/api/guesses'&&request.method==='POST')return json({error:'Standalone guess submission has been retired. Submit the entire matchup together.'},409);
      if(url.pathname==='/api/guesses'&&request.method==='GET')return baseWorker.fetch(request,env,ctx);
      if(url.pathname==='/api/matchup-submission'&&request.method==='POST'){
        const body=await request.json(),allowed=await effectiveMatch(env,body.match_id,{preview:session.is_test===true});
        if(!allowed||allowed.round!==body.round||allowed.songs.length!==2||!allowed.songs.includes(body.song_id))return json({error:'This submission does not match an active tournament matchup.'},400);
        if(body.round!=='play-in'&&session.is_test!==true){const state=await getTournamentState(env);if(state.published_rounds?.[body.round]!==true)return json({error:'This round has not been published yet.'},409)}
        const incoming=Array.isArray(body.guesses)?body.guesses:[];if(incoming.length!==2)return json({error:'Choose who submitted both songs before submitting the matchup.'},400);
        const valid=new Set((await participants(env)).filter(p=>!isTest(p)).map(p=>p.id)),bySong=new Map();
        for(const g of incoming){if(!allowed.songs.includes(g.song_id)||bySong.has(g.song_id))return json({error:'Submit exactly one guess for each song in the matchup.'},400);if(!valid.has(g.guessed_participant_id))return json({error:'Choose a valid Harry Man for both songs.'},400);bySong.set(g.song_id,{song_id:g.song_id,guessed_participant_id:g.guessed_participant_id})}
        if(allowed.songs.some(s=>!bySong.has(s)))return json({error:'Choose who submitted both songs before submitting the matchup.'},400);
        const r=await store(env,session.sub,'matchup-submit',{match_id:body.match_id,round:body.round,song_id:body.song_id,guesses:allowed.songs.map(s=>bySong.get(s)),is_test:session.is_test===true}),data=await r.json();return json(data,r.status);
      }
      if(url.pathname==='/api/tournament-state'&&request.method==='GET'){const state=await getTournamentState(env);return json({state:publicState(state),is_admin:session.is_test===true})}
      if(url.pathname==='/api/admin/round'&&request.method==='GET'){
        if(session.is_test!==true)return json({error:'Administrator access required.'},403);const round=url.searchParams.get('round')||'play-in',a=await aggregate(env,round),state=await getTournamentState(env),preview=round==='play-in'&&a.advancement_ready?buildR64(a.results):[];return json({aggregate:a,preview_matchups:preview,state});
      }
      if(url.pathname==='/api/admin/show-results'&&request.method==='POST'){
        if(session.is_test!==true)return json({error:'Administrator access required.'},403);const body=await request.json(),round=body.round||'play-in',a=await aggregate(env,round);if(!a.complete)return json({error:'Official voting is not complete for this round.'},409);const state=await getTournamentState(env);state.results_visible=state.results_visible||{};state.published_results=state.published_results||{};state.events=state.events||[];state.results_visible[round]=true;state.published_results[round]=a.results;state.events.push({event_id:'EVENT-'+crypto.randomUUID(),type:'results_published',round,published_at:new Date().toISOString(),published_by:session.sub});await saveTournamentState(env,state,`Publish HMPP results: ${round}`);return json({ok:true,state:publicState(state)});
      }
      if(url.pathname==='/api/admin/publish-round'&&request.method==='POST'){
        if(session.is_test!==true)return json({error:'Administrator access required.'},403);const body=await request.json();if(body.round!=='round-of-64')return json({error:'This build currently supports publishing the Round of 64 from Play-In results.'},400);const a=await aggregate(env,'play-in');if(!a.advancement_ready)return json({error:a.complete?'A tied Play-In must be resolved before Round of 64 can be published.':'Official Play-In voting is not complete yet.'},409);const matchups=buildR64(a.results),state=await getTournamentState(env);state.published_rounds=state.published_rounds||{};state.published_matchups=state.published_matchups||{};state.events=state.events||[];state.published_rounds['round-of-64']=true;state.published_matchups['round-of-64']=matchups;state.events.push({event_id:'EVENT-'+crypto.randomUUID(),type:'round_published',round:'round-of-64',source_round:'play-in',published_at:new Date().toISOString(),published_by:session.sub});await saveTournamentState(env,state,'Publish HMPP matchups: round-of-64');return json({ok:true,state:publicState(state),matchups});
      }
      return baseWorker.fetch(request,env,ctx);
    }catch(err){console.error(err);return json({error:'Server error.'},500)}
  }
};

export class ParticipantVoteStore extends BaseParticipantVoteStore {
  async fetch(request){
    const action=new URL(request.url).pathname.slice(1),body=await request.clone().json().catch(()=>({}));
    if(body.participant_id)await this.state.storage.put('participant_id',body.participant_id);if(typeof body.is_test==='boolean')await this.state.storage.put('is_test',body.is_test);
    if(action==='state'){
      let votes=(await this.state.storage.get('votes'))||{},guesses=(await this.state.storage.get('guesses'))||{},reset=false;
      if(body.participant_id==='test-voter'&&(await this.state.storage.get(RESET_MARKER))!==true){const bv=Object.keys(votes).length,bg=Object.keys(guesses).length;votes=Object.fromEntries(Object.entries(votes).filter(([,v])=>v.round!=='round-of-64'));guesses=Object.fromEntries(Object.entries(guesses).filter(([,g])=>g.round!=='round-of-64'));await this.state.storage.put('votes',votes);await this.state.storage.put('guesses',guesses);await this.state.storage.put(RESET_MARKER,true);reset=true;if(Object.keys(votes).length!==bv||Object.keys(guesses).length!==bg)await this.state.storage.setAlarm(Date.now()+1000)}
      return json({votes,guesses,test_round1_reset_applied:reset});
    }
    if(action==='matchup-submit'){
      const votes=(await this.state.storage.get('votes'))||{},guesses=(await this.state.storage.get('guesses'))||{},existingVote=votes[body.match_id],incoming=Array.isArray(body.guesses)?body.guesses:[];
      if(existingVote&&existingVote.song_id!==body.song_id)return json({error:'A vote has already been submitted for this matchup.'},409);for(const g of incoming){const ex=guesses[g.song_id];if(ex&&ex.guessed_participant_id!==g.guessed_participant_id)return json({error:'A submitter guess has already been submitted for this song.'},409)}
      const test=(await this.state.storage.get('is_test'))===true,matchupId=existingVote?.matchup_submission_id||((test?'TESTMATCHUP-':'MATCHUP-')+crypto.randomUUID()),submittedAt=new Date().toISOString();let vote=existingVote;
      if(!vote){vote={vote_submission_id:(test?'TESTVOTE-':'VOTE-')+crypto.randomUUID(),matchup_submission_id:matchupId,match_id:body.match_id,round:body.round,song_id:body.song_id,submitted_at:submittedAt,vote_pool:test?'test':'official',excluded_from_official_totals:test};votes[body.match_id]=vote}else if(!vote.matchup_submission_id){vote={...vote,matchup_submission_id:matchupId};votes[body.match_id]=vote}
      const returned=[];for(const g of incoming){if(guesses[g.song_id]){returned.push(guesses[g.song_id]);continue}const rec={guess_submission_id:(test?'TESTGUESS-':'GUESS-')+crypto.randomUUID(),guess_batch_id:matchupId,matchup_submission_id:matchupId,match_id:body.match_id,round:body.round,song_id:g.song_id,guessed_participant_id:g.guessed_participant_id,match_vote_song_id_at_submission:vote.song_id,match_vote_submission_id:vote.vote_submission_id,submitted_at:submittedAt,guess_pool:test?'test':'official',excluded_from_official_guess_stats:test};guesses[g.song_id]=rec;returned.push(rec)}
      await this.state.storage.put('votes',votes);await this.state.storage.put('guesses',guesses);await this.state.storage.setAlarm(Date.now()+FIVE_MINUTES);return json({ok:true,matchup_submission_id:matchupId,vote,guesses:returned});
    }
    if(action==='admin-state')return json({state:(await this.state.storage.get('tournament_state'))||defaultTournamentState()});
    if(action==='admin-set'){const state=body.state||defaultTournamentState();await this.state.storage.put('tournament_state',state);return json({ok:true,state})}
    return super.fetch(request);
  }
  async flushGit(){
    const votes=(await this.state.storage.get('votes'))||{},guesses=(await this.state.storage.get('guesses'))||{},participantId=(await this.state.storage.get('participant_id'))||'participant',test=(await this.state.storage.get('is_test'))===true;
    if(participantId===ADMIN_STORE_ID)return;
    const payload={schema_version:4,tournament:'HMPP-2026',participant_id:participantId,vote_pool:test?'test':'official',excluded_from_official_totals:test,guess_pool:test?'test':'official',excluded_from_official_guess_stats:test,updated_at:new Date().toISOString(),votes,guesses};
    const path=test?`data/2026/test-votes/by-participant/${participantId}.json`:`data/2026/votes/by-participant/${participantId}.json`;await writeGitJson(this.env,path,payload,`${test?'Sync HMPP TEST votes':'Sync HMPP votes'}: ${participantId}`);
  }
}
